version: '3.8'

services:
  backend:
    container_name: simpleapistud
    build:
      context: ./simple-api-student-main
    networks:
      - tp1
    depends_on:
      - database
    environment: 
      - URL=tp1bdd:5432
      - USERNAME=usr
      - PASSWORD=pwd
      - DB=db

  database:
    container_name: tp1bdd
    build: ./dataBase
    networks:
      - tp1
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd

  httpd:
    build:
      context: ./http
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - tp1
    depends_on:
      - frontend

  frontend: 
    build:
      context: ./devops-front-main
    networks:
      - tp1
    depends_on:
      - backend

networks:
  tp1:

volumes:
  db: