
- name: Run DB
  community.docker.docker_container:
    name: tp1bdd
    networks:
    - name: networkDevops
    image: scorpion6912/tp2-devops-database:latest
    env:
      password: "{{ POSTGRES_PASSWORD }}"
      username: "{{ POSTGRES_USER }}"
      db: "{{ POSTGRES_DB }}"
      url: "{{ URL }}"