
- name: Run DB
  community.docker.docker_container:
    name: tp1bdd
    pull: true
    recreate: true
    networks:
    - name: networkDevops
    image: scorpion6912/tp2-devops-database:latest
    env:
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"