
- name: Run backend
  community.docker.docker_container:
    name: simpleapistud
    networks:
    - name: networkDevops
    image: scorpion6912/tp2-devops-simple-api-student-main
    env:
      password: "{{ POSTGRES_PASSWORD }}"
      username: "{{ POSTGRES_USER }}"
      db: "{{ POSTGRES_DB }}"
      url: "{{ URL }}"