
- name: Run HTTPD
  community.docker.docker_container:
    name: httpd-1
    pull: true
    recreate: true
    networks:
    - name: networkDevops
    ports:
    - "80:80"
    - "8080:8080"
    image:  scorpion6912/tp2-devops-http-front